pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "dorapizza/finalproject_3"
        SERVER_IP = "54.116.1.59"
        CONTAINER_NAME = "finalproject_3"
    }

    tools {
        jdk 'jdk17'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build with Gradle') {
            steps {
                dir('finalProject_3') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew clean build -x test'
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                dir('finalProject_3') {
                    withCredentials([usernamePassword(
                        credentialsId: 'dockerhub_info',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )]) {
                        sh '''
                            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                            docker build --provenance=false -t $DOCKER_IMAGE:latest .
                            docker push $DOCKER_IMAGE:latest
                        '''
                    }
                }
            }
        }

        stage('Deploy to Server') {
            steps {
                sshagent(['SERVER_SSH_KEY']) {
                    sh '''
      ssh -o StrictHostKeyChecking=no ubuntu@$SERVER_IP \
          "docker stop $CONTAINER_NAME || true && \
           docker rm $CONTAINER_NAME || true && \
           docker pull $DOCKER_IMAGE:latest && \
           docker run -d --restart always --name $CONTAINER_NAME \
           -p 9080:9080 \
           -v /home/ubuntu/config/application.yml:/app/config/application.yml \
           -v /home/ubuntu/secrets/serviceAccountKey.json:/home/ubuntu/secrets/serviceAccountKey.json \
           -v /home/ubuntu/uploads/file_upload:/app/file_upload \
           -v /home/ubuntu/uploads/file_photoupload:/app/file_photoupload \
           -v /home/ubuntu/uploads/file_images:/app/file_images \
           -v /home/ubuntu/uploads/file_profile:/app/file_profile \
           -v /home/ubuntu/uploads/file_adminupload:/app/file_adminupload \
           -v /home/ubuntu/uploads/file_reports:/app/file_reports \
           -v /home/ubuntu/uploads/file_emailattachfile:/app/file_emailattachfile \
           $DOCKER_IMAGE:latest"
  '''
                }
            }
        }
    }

    post {
        success {
            echo "Deployment completed successfully."
        }
        failure {
            echo "Deployment failed."
        }
    }
}
